tosca_definitions_version: alien_dsl_2_0_0

#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

metadata:
  template_name: org.ystia.munge.ansible
  template_version: 2.1.0-M4
  template_author: Ystia


imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - yorc-types:1.0.0

node_types:
  org.ystia.munge.ansible.nodes.Munge:
    derived_from: tosca.nodes.SoftwareComponent
    metadata:
      icon: /images/munge-icon.png
    properties:
      properties:
      key:
        type: string
        default: ""
        required: false
        description: >
          Base64-encoded Munge secret key. If not provided a key will be generated automatically using a pseudo-random seed.
    interfaces:
      Standard:
        create:
          inputs:
            KEY: {get_property: [SELF, key]}
          implementation: playbooks/create.yaml
        start: playbooks/start.yaml
        stop: playbooks/stop.yaml
