- name: Download plugin
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: Download plugin archive
      get_url:
        url: "{{ download_url }}"
        dest: "/tmp/alien4cloud-yorc-provider_{{ INSTANCE }}.zip"

- name: Upload plugin into Alien
  hosts: all
  strategy: linear
  become: true
  environment:
    # We are assuming that Alien is accessible without proxies
    # as actually this component is hosted on the Alien node 
    # (so they are on the same host)
    http_proxy: ""
    HTTP_PROXY: ""
    https_proxy: ""
    HTTPS_PROXY: ""
  tasks:
    - name: "Login onto A4C using {{ alien_url }}/login?username={{ alien_user }}&password={{ alien_password }}&submit=Login"
      uri:
        url: "{{ alien_url }}/login?username={{ alien_user }}&password={{ alien_password }}&submit=Login"
        method: POST
        return_content: yes
        status_code: 302
        validate_certs: no
        headers:
          Content-Type: "application/x-www-form-urlencoded"
      register: login

    - set_fact:
        session_id: "{{ login.set_cookie.split(';')[0] }}"

    - name: Delete Yorc default plugin coming with Alien4Cloud
      shell: "env -i curl -k -X DELETE -H 'cookie: {{ session_id }}' '{{ alien_url }}/rest/latest/plugins/alien4cloud-yorc-provider'"

    - name: Upload plugin archive to A4C
      shell: "env -i curl -k -X POST -H 'cookie: {{ session_id }}' -F file=@/tmp/alien4cloud-yorc-provider_{{ INSTANCE }}.zip '{{ alien_url }}/rest/latest/plugins'"
