tosca_definitions_version: alien_dsl_2_0_0

#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

metadata:
  template_name: org.ystia.docker.ansible
  template_version: 2.1.0-SNAPSHOT
  template_author: Ystia


imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - yorc-types:1.0.0

node_types:
  org.ystia.munge.ansible.nodes.Docker:
    derived_from: tosca.nodes.SoftwareComponent
    metadata:
      icon: /images/docker-icon.png
    properties:
      proxy_url:
        type: string
        default: ""
        required: false
        description: >
          http proxy used by docker daemon
        constraints:
          - pattern: "https?://.*:[0-9]+/?"
    interfaces:
      Standard:
        create:
          implementation: playbooks/create.yaml
        configure:
          inputs:
            PROXY_URL: {get_property: [SELF, proxy_url]}
          implementation: playbooks/configure.yaml
        start: playbooks/start.yaml
        stop: playbooks/stop.yaml
