tosca_definitions_version: alien_dsl_2_0_0

#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

metadata:
  template_name: org.ystia.docker.ansible
  template_version: 2.2.0-SNAPSHOT
  template_author: Ystia

imports:
  - tosca-normative-types:1.0.0-ALIEN20
  - yorc-types:1.1.0
  - docker-types:2.2.0-SM6

node_types:
  org.ystia.docker.ansible.nodes.Docker:
    derived_from: tosca.nodes.SoftwareComponent
    metadata:
      icon: /images/docker-icon.png
    properties:
      docker_version:
        type: string
        default: ""
        required: false
        description: >
          docker package version
      repository_url:
        type: string
        required: false
        description: >
          repository url to install docker from. This property is optional and the default value is 'https://download.docker.com/linux/centos/7/$basearch/stable'
          on Redhat systems and 'deb https://download.docker.com/linux/ubuntu xenial stable' on Debian ones.
        constraints:
          - pattern: ".*https?://.*"
      docker_gpgkey:
        type: string
        required: false
        description: >
         gpg key url to use for docker package installation. This property is optional and the default value is 'https://download.docker.com/linux/centos/gpg'
         on Redhat systems and 'https://download.docker.com/linux/ubuntu/gpg' on Debian ones.
        constraints:
          - pattern: ".*https?://.*"
    capabilities:
       host: org.alien4cloud.extended.container.capabilities.ApplicationHost
    interfaces:
      Standard:
        create:
          inputs:
            DOCKER_VERSION: {get_property: [SELF, docker_version]}
            REPOSITORY_URL: {get_property: [SELF, repository_url]}
            DOCKER_GPGKEY: {get_property: [SELF, docker_gpgkey]}
          implementation: playbooks/create.yaml
        configure:
          implementation: playbooks/configure.yaml
        start: playbooks/start.yaml
        stop: playbooks/stop.yaml
