
- name: Install Vault
  hosts: all
  strategy: free
  become: true
  tasks:
    - name: RedHat - install prerequisites
      yum:
        name: ["zip", "unzip", "python34-pip"]
        state: present
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Debian - install prerequisites
      apt:
        name: ["zip", "unzip", "python3-pip", "acl"]
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Ensure python OpenSSL dependencies are installed.
      pip:
        name: pyOpenSSL>18.0.0
        state: present

    - name: Download and extract Vault binary
      unarchive:
        src: "https://releases.hashicorp.com/vault/{{ VERSION }}/vault_{{ VERSION }}_linux_amd64.zip"
        dest: "{{ INSTALL_DIR }}"
        remote_src: yes
    
    - name: create Vault group
      group: 
        name: vault

    - name: create Vault user
      user:
        name: vault
        system: true
        group: vault

    - name: Create Vault config dir
      file:
        path: "{{ CONFIG_DIR }}"
        state: directory
        owner: vault
        group: vault
        mode: 0750

    - name: Create Vault systemd unit
      template:
        src: "vault.service.j2"
        dest: "/etc/systemd/system/vault.service"
        mode: 0600

    - name: Ensure Vault service is enabled and stopped
      service:
        name: vault
        state: stopped
        enabled: yes
        daemon_reload: yes