#
# Ystia Forge
# Copyright (C) 2018 Bull S. A. S. - Bull, Rue Jean Jaures, B.P.68, 78340, Les Clayes-sous-Bois, France.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
#

- name: Configure docker proxy
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: create docker.service.d directory
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
      when:
        - PROXY_URL is defined
        - PROXY_URL != ''

    - name: Generate http-proxy.conf file
      template:
        src: "http-proxy.conf.j2"
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
      when:
        - PROXY_URL is defined
        - PROXY_URL != ''

